ignorePatterns:
  - '**/*.lock'
  - '**/*.lock.json'
  - '**/*.lockb'
  - '**/node_modules'
  - '**/.env'
  - '**/edgedb/lib/**'
  - '**/admin/lib/**'

checkCommands:
  fix: pnpm run fix
  lint: pnpm run test:format && pnpm run test:lint
  types: pnpm run test:typecheck
